FROM ubuntu:latest
LABEL maintainer "Michal Kosik"


RUN apt-get update -y && apt-get install net-tools isc-dhcp-server -y

WORKDIR /etc/dhcp/
COPY dhcp.conf /etc/dhcp/


ENTRYPOINT ["service", "dhcpd", "start"]
